name: Java CI with Selenide

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: java version
        run: java --version

      - name: Install ChromeDriver
        run: |
          wget https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/116.0.5845.96/linux64/chrome-linux64.zip
          unzip chrome-linux64.zip
          chmod +x chrome-linux64
          sudo mv chrome-linux64 /usr/local/bin/

      - name: Set ChromeOptions for Selenide
        run: mvn -X clean test -Dchromeoptions.args="--no-sandbox,--disable-extensions,--disable-dev-shm-usage,--user-agent=Chrome/116.0.5845.9" -Dchromeoptions.prefs="homepage=https://example.com,\"intl.accept_languages=en-US,en,es\""

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # You can change this to your desired Java version

      - name: Build with Maven
        run: mvn clean install

      - name: Run Selenide Tests
        run: mvn test
