name: Java CI with Selenide

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install ChromeDriver
        run: |
          wget https://chromedriver.storage.googleapis.com/100.0.4896.20/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          chmod +x chromedriver
          sudo mv chromedriver /usr/local/bin/

      - name: Set ChromeOptions for Selenide
        run: mvn -X clean test -Dchromeoptions.args="--no-sandbox,--disable-extensions,--disable-dev-shm-usage,--user-agent=Chrome/100.0.4896.20" -Dchromeoptions.prefs="homepage=https://example.com,\"intl.accept_languages=en-US,en,es\""

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # You can change this to your desired Java version

      - name: Build with Maven
        run: mvn clean install

      - name: Run Selenide Tests
        run: mvn test
